version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # 👈 Important
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true" # just for now, so you avoid topic issues
      ALLOW_PLAINTEXT_LISTENER: "yes"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # topic-creator:
  #   image: bitnami/kafka:3.7
  #   depends_on:
  #     - kafka
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: |
  #     "
  #     echo '⏳ Waiting for Kafka to be ready...';
  #     sleep 10;  # crude wait; better would be a real health check
  #     kafka-topics.sh --create \
  #       --if-not-exists \
  #       --bootstrap-server kafka:9092 \
  #       --replication-factor 1 \
  #       --partitions 1 \
  #       --topic audio_ready && \
  #     echo '✅ Topic created: audio_ready'
  #     "
